"""create new_flat

Revision ID: 328c495f6160
Revises:
Create Date: 2021-08-03 15:40:55.600845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328c495f6160'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new__flat',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('num_rooms', sa.Integer(), nullable=True),
                    sa.Column('floor', sa.Integer(), nullable=True),
                    sa.Column('link', sa.String(), nullable=True),
                    sa.Column('area', sa.Integer(), nullable=True),
                    sa.Column('material', sa.Integer(), nullable=True),
                    sa.Column('metro', sa.String(), nullable=True),
                    sa.Column('district', sa.String(), nullable=True),
                    sa.Column('street', sa.String(), nullable=True),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.Column('commission', sa.Integer(), nullable=True),
                    sa.Column('deposit', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('link')
                    )
    op.drop_table('sqlite_stat4')
    op.drop_table('sqlite_stat1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_stat1',
                    sa.Column('tbl', sa.NullType(), nullable=True),
                    sa.Column('idx', sa.NullType(), nullable=True),
                    sa.Column('stat', sa.NullType(), nullable=True)
                    )
    op.create_table('sqlite_stat4',
                    sa.Column('tbl', sa.NullType(), nullable=True),
                    sa.Column('idx', sa.NullType(), nullable=True),
                    sa.Column('neq', sa.NullType(), nullable=True),
                    sa.Column('nlt', sa.NullType(), nullable=True),
                    sa.Column('ndlt', sa.NullType(), nullable=True),
                    sa.Column('sample', sa.NullType(), nullable=True)
                    )
    op.drop_table('new__flat')
    # ### end Alembic commands ###
