"""drop tables

Revision ID: 9a2a9313a1ac
Revises: 466d4b37c743
Create Date: 2021-08-03 16:17:09.158457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2a9313a1ac'
down_revision = '466d4b37c743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    op.drop_table('flat')
    op.drop_table('payment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('price', sa.INTEGER(), nullable=True),
                    sa.Column('commission', sa.INTEGER(), nullable=True),
                    sa.Column('deposit', sa.INTEGER(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('flat',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('location_id', sa.INTEGER(), nullable=False),
                    sa.Column('payment_id', sa.INTEGER(), nullable=False),
                    sa.Column('num_rooms', sa.INTEGER(), nullable=True),
                    sa.Column('floor', sa.INTEGER(), nullable=True),
                    sa.Column('is_studio', sa.BOOLEAN(), nullable=False),
                    sa.Column('link', sa.VARCHAR(), nullable=True),
                    sa.Column('area', sa.INTEGER(), nullable=True),
                    sa.Column('material', sa.INTEGER(), nullable=True),
                    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
                    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('link')
                    )
    op.create_table('location',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('metro', sa.VARCHAR(), nullable=True),
                    sa.Column('district', sa.VARCHAR(), nullable=True),
                    sa.Column('street', sa.VARCHAR(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
